// Type definitions for @via-profit-services/subscriptions
// Project: git@github.com:via-profit-services/subscriptions
// Definitions by: Via Profit <https://github.com/via-profit-services>
// Warning: This is not autogenerated definitions!

/// <reference types="node" />
declare module '@via-profit-services/core' {
  import { Redis } from 'ioredis';

  interface Context {

    /**
     * Already configures instance of ioRedis
     * @see: https://github.com/luin/ioredis
     */
    redis: Redis;
  }
  
}

declare module '@via-profit-services/redis' {
  import { RedisOptions, Redis } from 'ioredis';
  import { Middleware, Logger } from '@via-profit-services/core';

  export type InitialProps = RedisOptions;
  export type RedisFactory = (options: RedisOptions, logger?: Logger) => Redis;
  export type RedisMiddlewareFactory = (props?: InitialProps) => Middleware;

  /**
   * ioRedis factory
   * @see: https://github.com/luin/ioredis
   */
  export const redisFactory: RedisFactory;
  /**
   * Middleware for @via-profit-services/core
   */
  export const factory: RedisMiddlewareFactory;
}